export { default as ThreeBackground } from './ThreeBackground/ThreeBackground';
export { default as Navbar } from './Navbar/Navbar';
export { default as Hero } from './Hero/Hero';
export { default as Ticker } from './Ticker/Ticker';
export { default as BentoGrid } from './BentoGrid/BentoGrid';
export { default as Projects } from './Projects/Projects';
export { default as Experience } from './Experience/Experience';
export { default as Skills } from './Skills/Skills';
export { default as Footer } from './Footer/Footer';
